// Generated by python/tools/generate_science_catalog.py; do not edit by hand.
#pragma once
#include <vector>
struct ScienceParameterDef { const char* name; const char* label; const char* value; const char* kind; bool required; };
struct ScienceToolDef { const char* id; const char* title; const char* help; const char* category; std::vector<ScienceParameterDef> parameters; };
inline const std::vector<ScienceToolDef>& scienceToolCatalog()
{
    static const std::vector<ScienceToolDef> tools = {
        {"msd", "Mean-square displacement", "Time-origin-averaged MSD and Cartesian displacement covariance.\n\nAtom ordering must be stable. Unwrapped coordinates are recommended.\nWith wrapped=True, unwrap successive displacements in a FIXED cell using\nits shortest image; sampling must resolve motion below the MIC ambiguity.\nVariable-cell trajectories must first be mapped to an explicit reference\nframe. remove_drift subtracts the geometric centroid at every frame.\nCovariance is <dr_a dr_b>, not a covariance about the mean displacement.", "Trajectories and transport", {
            {"positions", "Atomic positions (Angstrom)", "", "data", true},
            {"timestep_fs", "Sampling interval (fs)", "1.0", "float", true},
            {"cell", "Cell vectors (Angstrom)", "", "data", false},
            {"pbc", "Periodic boundaries", "[true, true, true]", "axes", false},
            {"wrapped", "Unwrap periodic positions", "false", "bool", false},
            {"remove_drift", "Remove geometric-centroid drift", "false", "bool", false},
            {"max_lag", "Maximum lag (frames)", "", "int", false},
        }},
        {"diffusion", "Diffusion coefficient", "Einstein diffusion from an explicitly selected diffusive time interval.\n\nD = slope/(2*d); input MSD must sum ONLY the d selected directions.\nReports slope, intercept, R-squared and OLS fit uncertainty. Overlapping\ntime origins correlate MSD samples: the OLS uncertainty is NOT a physical\nconfidence interval. Use independent trajectories/block estimates for that.\nA linear fit alone does not establish the diffusive regime.", "Trajectories and transport", {
            {"lag_fs", "Lag times (fs)", "", "data", true},
            {"msd_A2", "Mean-square displacements (Angstrom squared)", "", "data", true},
            {"fit_range_fs", "Fit interval (fs)", "[0.0, 0.0]", "range", true},
            {"dimensions", "Diffusion dimensions", "3", "int", false},
        }},
        {"vacf", "Velocity autocorrelation", "Unbiased time-origin average of v(t) dot v(t+lag), per atom.\n\nremove_drift removes each frame's geometric mean velocity, not its\nmass-weighted centre-of-mass velocity. Units before normalization: A^2/fs^2.", "Trajectories and transport", {
            {"velocities", "Velocities (Angstrom/fs)", "", "data", true},
            {"timestep_fs", "Sampling interval (fs)", "1.0", "float", true},
            {"max_lag", "Maximum lag (frames)", "", "int", false},
            {"remove_drift", "Remove geometric-centroid drift", "false", "bool", false},
            {"normalize", "Normalize to the zero-lag value", "false", "bool", false},
        }},
        {"vibrational-spectrum", "Trajectory vibrational spectrum", "One-sided velocity power spectrum, the Fourier partner of velocity correlation.\n\nUses a nonnegative periodogram, with optional atomic-mass weighting, and\nreturns unit-integral spectral weight per THz. This is a classical velocity\nspectrum, not quantum neutron/IR/Raman intensity. Resolution and Nyquist\nfrequency are determined by duration and sampling; zero padding adds no data.", "Trajectories and transport", {
            {"velocities", "Velocities (Angstrom/fs)", "", "data", true},
            {"timestep_fs", "Sampling interval (fs)", "1.0", "float", true},
            {"masses", "Atomic masses (amu)", "", "data", false},
            {"window", "Window function", "\"hann\"", "window", false},
            {"remove_mean", "Subtract mean velocity", "true", "bool", false},
        }},
        {"local-strain", "Local strain and D2min", "Least-squares deformation gradient, Green-Lagrange strain and D2min.\n\nAtom IDs/order must correspond. Neighbors are selected in the reference.\nD2min is the SUM of residual squared distances (A^2), not a per-neighbor\nmean. Rank-deficient environments have valid=False and NaN tensors; they\nmust not be interpreted as unstrained. Box deformation is included.", "Structure and defects", {
            {"reference", "Reference positions (Angstrom)", "", "data", true},
            {"current", "Current positions (Angstrom)", "", "data", true},
            {"cutoff_A", "Neighbor cutoff (Angstrom)", "3.0", "float", true},
            {"reference_cell", "Reference cell vectors (Angstrom)", "", "data", false},
            {"current_cell", "Current cell vectors (Angstrom)", "", "data", false},
            {"pbc", "Periodic boundaries", "[false, false, false]", "axes", false},
        }},
        {"centrosymmetry", "Centrosymmetry parameter", "Kelchner CSP: sum the N/2 smallest |r_i+r_j|^2 of all distinct pairs.\n\nSelects the nearest N neighbors within cutoff, including periodic images.\nThis is the conventional smallest-pair algorithm, not disjoint optimal\nmatching. Missing neighbors produce valid=False and NaN, not zero.", "Structure and defects", {
            {"positions", "Atomic positions (Angstrom)", "", "data", true},
            {"cutoff_A", "Neighbor cutoff (Angstrom)", "3.0", "float", true},
            {"neighbors", "Number of neighbors", "12", "int", false},
            {"cell", "Cell vectors (Angstrom)", "", "data", false},
            {"pbc", "Periodic boundaries", "[false, false, false]", "axes", false},
        }},
        {"bond-order", "Steinhardt bond order", "Local rotationally invariant Steinhardt q_l, with equal bond weights.\n\nq_l = sqrt(4*pi/(2*l+1) sum_m |mean_j Y_lm(r_ij)|^2).\nReports q_l (not w_l or neighbor-averaged qbar_l). No neighbors => invalid.", "Structure and defects", {
            {"positions", "Atomic positions (Angstrom)", "", "data", true},
            {"cutoff_A", "Neighbor cutoff (Angstrom)", "3.0", "float", true},
            {"degrees", "Spherical-harmonic degrees", "[4, 6]", "data", false},
            {"cell", "Cell vectors (Angstrom)", "", "data", false},
            {"pbc", "Periodic boundaries", "[false, false, false]", "axes", false},
        }},
        {"wigner-seitz", "Wigner-Seitz defects", "Assign each atom to its nearest reference site; count vacancies/excess atoms.\n\nA site with occupancy n>1 contributes n-1 interstitial excess atoms. This\ndoes not identify a unique interstitial atom within that site. A supplied\ncurrent_cell maps homogeneous box deformation back to the reference cell.\nTies choose the lowest site index and are flagged for inspection.", "Structure and defects", {
            {"reference_sites", "Reference lattice sites (Angstrom)", "", "data", true},
            {"positions", "Atomic positions (Angstrom)", "", "data", true},
            {"cell", "Cell vectors (Angstrom)", "", "data", false},
            {"current_cell", "Current cell vectors (Angstrom)", "", "data", false},
            {"pbc", "Periodic boundaries", "[false, false, false]", "axes", false},
        }},
        {"structure-factor", "Static structure factor", "S(q)=<|sum_j b_j exp(i q.r_j)|^2>/sum_j |b_j|^2.\n\nPositions have shape (atoms,3) or (frames,atoms,3). q vectors are Cartesian\nradians/A (include 2*pi in reciprocal lattice vectors). Equal weights give\nS(0)=N. No forward-scattering subtraction, powder average or quantum effects\nare implied. Use commensurate q for wrapped periodic coordinates.", "Reciprocal space", {
            {"positions", "Atomic positions (Angstrom)", "", "data", true},
            {"q_vectors", "Scattering vectors (radians/Angstrom)", "", "data", true},
            {"weights", "Weights", "", "data", false},
        }},
        {"band-gap", "Band gap and band edges", "Sampled band edges and smallest same-spin direct gap, relative to E_F.\n\nShape is (k,band) or (spin,k,band). Detects a metal when a band crosses E_F\non the supplied mesh, or a sampled state lies within tolerance of E_F.\nA sparse mesh can miss crossings/extrema. Smearing occupations are not\ninterpreted here, and the direct gap is not an optical excitation energy.", "Electronic structure", {
            {"energies_eV", "Energies (eV)", "", "data", true},
            {"fermi_eV", "Fermi energy (eV)", "0.0", "float", true},
            {"tolerance_eV", "Fermi-level tolerance (eV)", "1e-06", "float", false},
        }},
        {"effective-mass", "Effective-mass tensor", "Fit E=E0+g.dk+1/2 dk.H.dk; return signed principal masses in m_e.\n\nk is Cartesian wavevector in radians/A, not fractional reciprocal position\nor path length. Use a small 3D neighborhood of a band extremum, with one\nconsistently tracked band. Negative masses describe valence curvature;\npositive hole masses are their negatives. This is a local quadratic model.", "Electronic structure", {
            {"kpoints_inv_A", "Wavevectors (radians/Angstrom)", "", "data", true},
            {"energies_eV", "Energies (eV)", "", "data", true},
            {"center_inv_A", "Expansion center (radians/Angstrom)", "[0.0, 0.0, 0.0]", "vector", true},
        }},
        {"work-function", "Work function", "Phi=<V_vac>-E_F for a user-selected vacuum interval of a planar potential.\n\nSupply an electron potential-energy profile with a consistent reference,\ne.g. the appropriate VASP LOCPOT channel. A linear-fit slope and spread flag\na poorly converged/nonflat vacuum. Calculate the two slab faces separately.\nThis does not insert dipole corrections or detect vacuum automatically.", "Electronic structure", {
            {"distance_A", "Profile distances (Angstrom)", "", "data", true},
            {"potential_eV", "Potential-energy profile (eV)", "", "data", true},
            {"fermi_eV", "Fermi energy (eV)", "0.0", "float", true},
            {"vacuum_range_A", "Vacuum interval (Angstrom)", "[0.0, 0.0]", "range", true},
            {"max_slope_eV_per_A", "Vacuum slope threshold (eV/Angstrom)", "0.01", "float", false},
        }},
        {"equation-of-state", "Equation of state", "Third-order Birch-Murnaghan E(V) fit; energy and volume must share a cell basis.\n\nRequires at least five distinct positive volumes bracketing the fitted\nminimum. Returns bulk modulus and pressure derivative, residuals and fit\ncovariance (a numerical diagnostic, not model/convergence uncertainty).", "Thermal and mechanical", {
            {"volumes_A3", "Volumes (cubic Angstrom)", "", "data", true},
            {"energies_eV", "Energies (eV)", "", "data", true},
        }},
        {"elastic-tensor", "Elastic tensor and moduli", "Fit sigma=sigma0+C epsilon with engineering-Voigt order xx,yy,zz,yz,xz,xy.\n\nStrain shears are 2*epsilon_ij; stress shears are sigma_ij, with tension\npositive. Input stresses are GPa, not eV/A^3 or pressure-positive outputs.\nRequires a full-rank strain design including an intercept. Symmetrizes C\nand reports the antisymmetric mismatch and residual. Stability is the\npositive-definiteness test appropriate to small strain at zero prestress.", "Thermal and mechanical", {
            {"strains", "Engineering-Voigt strains", "", "data", true},
            {"stresses_GPa", "Engineering-Voigt stresses (GPa)", "", "data", true},
        }},
        {"phonon-dos", "Phonon density of states", "Gaussian harmonic DOS, normalized to number of branches per cell.\n\nInput is (qpoints,branches) in eV with negative energies denoting imaginary\nfrequencies. Those are retained on the negative axis; they are not stable\nmodes. Finite plot bounds can truncate Gaussian tails; enclosed weight is\nreturned without silently renormalizing the plotted curve.", "Thermal and mechanical", {
            {"energies_eV", "Energies (eV)", "", "data", true},
            {"energy_grid_eV", "Output energy grid (eV)", "", "data", true},
            {"sigma_eV", "Gaussian broadening (eV)", "0.001", "float", false},
            {"weights", "Weights", "", "data", false},
        }},
        {"harmonic-thermodynamics", "Harmonic thermodynamics", "Harmonic F,U,S,Cv per cell, including zero-point energy.\n\nNegative modes below -tolerance are rejected. Modes within +/-tolerance\n(e.g. exact Gamma acoustic zeros) are omitted and their weight reported;\nuse a converged q mesh. Outputs eV/cell and eV/(cell K), not per mole.\nElectronic, configurational and anharmonic contributions are excluded.", "Thermal and mechanical", {
            {"energies_eV", "Energies (eV)", "", "data", true},
            {"temperatures_K", "Temperatures (K)", "", "data", true},
            {"weights", "Weights", "", "data", false},
            {"zero_tolerance_eV", "Zero-mode tolerance (eV)", "1e-08", "float", false},
        }},
        {"neb", "NEB migration path", "Optimize a fixed-cell climbing-image NEB using ASE's improved tangent.\n\nEndpoints must already be relaxed, have identical cell/species/order, and\ndescribe the intended atom mapping. Factory is called separately for EVERY\nimage (external calculators must also use distinct working directories).\nBarriers are sampled image energies; convergence and endpoint forces are\nreported rather than assumed. mic=True chooses shortest periodic paths.", "Simulation", {
            {"initial", "Initial relaxed structure", "", "structure", true},
            {"final", "Final relaxed structure", "", "structure", true},
            {"calculator_factory", "ASE calculator for each image", "{\"module\": \"ase.calculators.emt\", \"attribute\": \"EMT\"}", "calculator", true},
            {"images", "Number of images (including endpoints)", "7", "int", false},
            {"fmax", "Force tolerance (eV/Angstrom)", "0.03", "float", false},
            {"steps", "Maximum optimization steps", "300", "int", false},
            {"spring_eV_per_A2", "Spring constant (eV/Angstrom squared)", "0.1", "float", false},
            {"climb", "Use climbing image", "true", "bool", false},
            {"mic", "Use shortest periodic interpolation", "false", "bool", false},
        }},
        {"nvt", "NVT dynamics", "Langevin NVT with a thermostat relaxation time in fs and reproducible seed.\n\nReturns temperatures, physical energies, frames and velocities. Physical\nenergy is not conserved under a thermostat. COM is not constrained; remove\nany unwanted drift explicitly during analysis. Equilibration is not inferred.", "Simulation", {
            {"structure", "Structure", "", "structure", true},
            {"calculator", "ASE calculator", "{\"module\": \"ase.calculators.emt\", \"attribute\": \"EMT\"}", "calculator", true},
            {"steps", "Integration steps", "1000", "int", false},
            {"timestep_fs", "Integration timestep (fs)", "1.0", "float", false},
            {"temperature_K", "Target temperature (K)", "300.0", "float", false},
            {"thermostat_fs", "Thermostat relaxation time (fs)", "100.0", "float", false},
            {"seed", "Random seed", "0", "int", false},
            {"sample_interval", "Save a frame every N steps", "10", "int", false},
        }},
        {"npt", "NPT dynamics", "Isotropic Martyna-Tobias-Klein NPT via ASE, pressure positive in compression.\n\nCell volume changes while shape remains fixed. A stress-capable calculator\nis required. Finite runs must be checked for equilibration, fluctuations and\nintegration convergence; instantaneous T and P need not equal targets.", "Simulation", {
            {"structure", "Structure", "", "structure", true},
            {"calculator", "ASE calculator", "{\"module\": \"ase.calculators.emt\", \"attribute\": \"EMT\"}", "calculator", true},
            {"steps", "Integration steps", "1000", "int", false},
            {"timestep_fs", "Integration timestep (fs)", "1.0", "float", false},
            {"temperature_K", "Target temperature (K)", "300.0", "float", false},
            {"pressure_GPa", "Target pressure (GPa)", "0.0", "float", false},
            {"thermostat_fs", "Thermostat relaxation time (fs)", "100.0", "float", false},
            {"barostat_fs", "Barostat relaxation time (fs)", "1000.0", "float", false},
            {"seed", "Random seed", "0", "int", false},
            {"sample_interval", "Save a frame every N steps", "10", "int", false},
        }},
        {"reciprocal-path", "Symmetry reciprocal-space path", "SeeK-path HPKOT high-symmetry path in the standardized primitive cell.\n\nReturns the primitive structure, reciprocal basis and segment endpoints so\nfractional k coordinates cannot be confused with the input supercell basis.\nNonmagnetic spatial symmetry is used; time_reversal controls path completion,\nnot a magnetic-space-group analysis. Disconnected segments remain explicit.", "Reciprocal space", {
            {"structure", "Structure", "", "structure", true},
            {"spacing_inv_A", "Reciprocal sampling spacing (1/Angstrom)", "0.025", "float", false},
            {"symprec_A", "Symmetry tolerance (Angstrom)", "1e-05", "float", false},
            {"time_reversal", "Assume time-reversal symmetry", "true", "bool", false},
        }},
    };
    return tools;
}
