"""Generate desktop tool metadata from the public scientific function signatures.

Run after changing a tool signature; --check detects a stale committed header.
The numerical implementation remains in Python, shared with CLI and desktop.
"""

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "python"))
from atomforge.science.workflows import tool_catalog

CATEGORIES = {
    "Structure and defects": ("local-strain", "centrosymmetry", "bond-order", "wigner-seitz"),
    "Trajectories and transport": ("msd", "diffusion", "vacf", "vibrational-spectrum"),
    "Electronic structure": ("band-gap", "effective-mass", "work-function"),
    "Reciprocal space": ("structure-factor", "reciprocal-path"),
    "Thermal and mechanical": ("equation-of-state", "elastic-tensor", "phonon-dos", "harmonic-thermodynamics"),
    "Simulation": ("neb", "nvt", "npt"),
}

LABELS = {
    "positions": "Atomic positions (Angstrom)", "velocities": "Velocities (Angstrom/fs)",
    "timestep_fs": "Sampling interval (fs)", "cell": "Cell vectors (Angstrom)",
    "pbc": "Periodic boundaries", "wrapped": "Unwrap periodic positions",
    "remove_drift": "Remove geometric-centroid drift", "max_lag": "Maximum lag (frames)",
    "lag_fs": "Lag times (fs)", "msd_A2": "Mean-square displacements (Angstrom squared)",
    "fit_range_fs": "Fit interval (fs)", "dimensions": "Diffusion dimensions",
    "normalize": "Normalize to the zero-lag value", "masses": "Atomic masses (amu)",
    "window": "Window function", "remove_mean": "Subtract mean velocity",
    "reference": "Reference positions (Angstrom)", "current": "Current positions (Angstrom)",
    "reference_sites": "Reference lattice sites (Angstrom)", "cutoff_A": "Neighbor cutoff (Angstrom)",
    "reference_cell": "Reference cell vectors (Angstrom)", "current_cell": "Current cell vectors (Angstrom)",
    "neighbors": "Number of neighbors", "degrees": "Spherical-harmonic degrees",
    "q_vectors": "Scattering vectors (radians/Angstrom)", "weights": "Weights",
    "energies_eV": "Energies (eV)", "fermi_eV": "Fermi energy (eV)",
    "tolerance_eV": "Fermi-level tolerance (eV)", "kpoints_inv_A": "Wavevectors (radians/Angstrom)",
    "center_inv_A": "Expansion center (radians/Angstrom)", "distance_A": "Profile distances (Angstrom)",
    "potential_eV": "Potential-energy profile (eV)", "vacuum_range_A": "Vacuum interval (Angstrom)",
    "max_slope_eV_per_A": "Vacuum slope threshold (eV/Angstrom)", "volumes_A3": "Volumes (cubic Angstrom)",
    "strains": "Engineering-Voigt strains", "stresses_GPa": "Engineering-Voigt stresses (GPa)",
    "energy_grid_eV": "Output energy grid (eV)", "sigma_eV": "Gaussian broadening (eV)",
    "temperatures_K": "Temperatures (K)", "zero_tolerance_eV": "Zero-mode tolerance (eV)",
    "initial": "Initial relaxed structure", "final": "Final relaxed structure", "structure": "Structure",
    "calculator": "ASE calculator", "calculator_factory": "ASE calculator for each image",
    "images": "Number of images (including endpoints)", "fmax": "Force tolerance (eV/Angstrom)",
    "steps": "Integration steps", "spring_eV_per_A2": "Spring constant (eV/Angstrom squared)",
    "climb": "Use climbing image", "mic": "Use shortest periodic interpolation",
    "temperature_K": "Target temperature (K)", "pressure_GPa": "Target pressure (GPa)",
    "thermostat_fs": "Thermostat relaxation time (fs)", "barostat_fs": "Barostat relaxation time (fs)",
    "seed": "Random seed", "sample_interval": "Save a frame every N steps",
    "spacing_inv_A": "Reciprocal sampling spacing (1/Angstrom)", "symprec_A": "Symmetry tolerance (Angstrom)",
    "time_reversal": "Assume time-reversal symmetry",
}


def generate():
    quote = lambda value: json.dumps(value, ensure_ascii=True)
    lines = ["// Generated by python/tools/generate_science_catalog.py; do not edit by hand.",
             "#pragma once", "#include <vector>",
             "struct ScienceParameterDef { const char* name; const char* label; const char* value; const char* kind; bool required; };",
             "struct ScienceToolDef { const char* id; const char* title; const char* help; const char* category; std::vector<ScienceParameterDef> parameters; };",
             "inline const std::vector<ScienceToolDef>& scienceToolCatalog()", "{",
             "    static const std::vector<ScienceToolDef> tools = {"]
    catalog = tool_catalog()
    assigned = [tool for members in CATEGORIES.values() for tool in members]
    if sorted(assigned) != sorted(tool["id"] for tool in catalog):
        raise ValueError("Every scientific tool must belong to exactly one Analysis category")
    for tool in catalog:
        category = next(name for name, members in CATEGORIES.items() if tool["id"] in members)
        lines.append("        {" + ", ".join(quote(tool[k]) for k in ("id", "name", "description")) + ", " + quote(category) + ", {")
        for field in tool["parameters"]:
            value = field["default"]
            name = field["name"]
            kind = "data"
            if name in ("initial", "final", "structure"):
                kind = "structure"
            elif name in ("calculator", "calculator_factory"):
                kind = "calculator"
                value = {"module": "ase.calculators.emt", "attribute": "EMT"}
            elif isinstance(value, bool):
                kind = "bool"
            elif isinstance(value, int) or name == "max_lag":
                kind = "int"
            elif isinstance(value, float) or name in ("timestep_fs", "cutoff_A", "fermi_eV"):
                kind = "float"
                if value is None:
                    value = {"timestep_fs": 1., "cutoff_A": 3., "fermi_eV": 0.}[name]
            elif isinstance(value, str):
                kind = "string"
            if name == "pbc":
                kind = "axes"
            elif name == "window":
                kind = "window"
            elif name in ("fit_range_fs", "vacuum_range_A"):
                kind = "range"
                value = [0., 0.]
            elif name == "center_inv_A":
                kind = "vector"
                value = [0., 0., 0.]
            label = LABELS[name]
            if tool["id"] in ("nvt", "npt") and name == "timestep_fs":
                label = "Integration timestep (fs)"
            if tool["id"] == "neb" and name == "steps":
                label = "Maximum optimization steps"
            literal = "" if value is None else json.dumps(value)
            lines.append("            {" + ", ".join((quote(name), quote(label), quote(literal), quote(kind),
                         "true" if field["required"] else "false")) + "},")
        lines.append("        }},")
    lines.extend(("    };", "    return tools;", "}", ""))
    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    output = ROOT / "src/ui/ScienceCatalog.h"
    text = generate()
    if args.check:
        if not output.exists() or output.read_text(encoding="utf-8") != text:
            raise SystemExit("Desktop scientific catalog is stale")
    else:
        output.write_text(text, encoding="utf-8")
    print("Scientific desktop catalog: 20 tools verified")
