"""Render the illustrated tutorial catalogue to LaTeX and check its assets.

Edit tutorials.json, then run this script with --write. Normal manual builds
check that the generated chapter still matches the catalogue.
"""
import argparse
import json
from pathlib import Path
import struct

MANUAL = Path(__file__).resolve().parents[1]


def image_size(path):
    """Read PNG/JPEG dimensions without adding a manual-build dependency."""
    data = path.read_bytes()
    if data[:8] == b"\x89PNG\r\n\x1a\n":
        return struct.unpack(">II", data[16:24])
    if data[:2] == b"\xff\xd8":
        offset = 2
        while offset < len(data):
            if data[offset] != 255:
                break
            while data[offset] == 255:
                offset += 1
            marker = data[offset]
            offset += 1
            if marker in (0xD8, 0xD9):
                continue
            length = int.from_bytes(data[offset:offset + 2], "big")
            if marker in (0xC0, 0xC1, 0xC2):
                height, width = struct.unpack(">HH", data[offset + 3:offset + 7])
                return width, height
            offset += length
    raise ValueError(f"Unsupported image: {path}")


def render():
    catalogue = json.loads((MANUAL / "tutorials.json").read_text(encoding="utf-8"))
    output = [r"% Generated by scripts/render_tutorials.py; edit tutorials.json."]
    output += [r"\chapter{Illustrated quick tutorials}\label{ch:tutorials}",
               "Each exercise starts from a named example or an explicit input. "
               "Use a working copy for edits. The numbered steps describe the target "
               "exercise; a screenshot may show the initial controls instead of the "
               "completed settings. Captions identify the captured state. Full parameter "
               "definitions remain in the builder, edit, and display control references.",
               "Screenshots are real Windows application captures. Cropping in LaTeX "
               "only isolates the relevant dialog or controls; it does not change their "
               "contents. Some dialogs need scrolling to reach lower controls. Scientific "
               "shape images are separately plotted from native builder output, as labelled."]
    ids = set()
    images = set()
    for group in catalogue["groups"]:
        output += [r"\clearpage", r"\section{" + group["title"] + "}"]
        for index, entry in enumerate(group["tutorials"]):
            if index:
                output.append(r"\clearpage")
            identity = entry["id"]
            if identity in ids:
                raise ValueError(f"Duplicate tutorial: {identity}")
            ids.add(identity)
            if len(entry["steps"]) < 2 or not entry["check"] or not entry["images"]:
                raise ValueError(f"Incomplete exercise: {identity}")
            output += [r"\subsection{" + entry["title"] + "}\\label{tutorial:" + identity + "}",
                       r"\textbf{Start here.} " + entry["start"]]
            for asset in entry["images"]:
                path = MANUAL / "figures" / asset["file"]
                width, height = image_size(path)
                left, top, right, bottom = asset.get("bounds", [0, 0, width, height])
                if not (0 <= left < right <= width and 0 <= top < bottom <= height):
                    raise ValueError(f"Invalid crop: {path}")
                # Convert the 96 dpi screenshot crop bounds to PDF points.
                # Scientific PNG figures use their full bounds (zero trim).
                trim = " ".join(f"{v * .75:g}bp" for v in
                                (left, height - bottom, width - right, top))
                images.add(asset["file"])
                output += [r"\begin{center}",
                           r"\includegraphics[width=\linewidth,height=.43\textheight,keepaspectratio,"
                           + "trim=" + trim + ",clip]{figures/" + asset["file"] + "}",
                           r"\par\small\textit{" + asset["caption"] + "}", r"\end{center}"]
            output.append(r"\begin{enumerate}")
            output += [r"\item " + step for step in entry["steps"]]
            output += [r"\end{enumerate}", r"\textbf{Check the result.} " + entry["check"]]
            if entry.get("options"):
                output += [r"\textbf{Try the options.} " + entry["options"]]
    required = set(catalogue["required_tutorials"])
    if required != ids:
        raise ValueError(f"Tutorial coverage mismatch: {required ^ ids}")
    return "\n\n".join(output) + "\n", len(ids), len(images)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    content, count, images = render()
    destination = MANUAL / "chapters/13-illustrated-tutorials.tex"
    if args.write:
        destination.write_text(content, encoding="utf-8")
    elif not destination.exists() or destination.read_text(encoding="utf-8") != content:
        raise SystemExit("Tutorial chapter is stale. Run render_tutorials.py --write.")
    print(f"Illustrated tutorials checked: {count} exercises, {images} image assets.")


if __name__ == "__main__":
    main()
