# Hold the lock until the child exits and propagate failures to the build tool.
if(NOT DEFINED ATOMFORGE_BUILD_LOCK OR ATOMFORGE_BUILD_LOCK STREQUAL "")
    message(FATAL_ERROR "Missing AtomForge build lock path")
endif()

set(_command)
set(_after_separator FALSE)
math(EXPR _last_argument "${CMAKE_ARGC} - 1")
foreach(_index RANGE 0 ${_last_argument})
    if(_after_separator)
        # Preserve literal semicolons inside a single command argument.
        string(REPLACE ";" "\\;" _argument "${CMAKE_ARGV${_index}}")
        list(APPEND _command "${_argument}")
    elseif(CMAKE_ARGV${_index} STREQUAL "--")
        set(_after_separator TRUE)
    endif()
endforeach()
if(NOT _command)
    message(FATAL_ERROR "Missing AtomForge build command")
endif()

file(LOCK "${ATOMFORGE_BUILD_LOCK}" GUARD PROCESS RESULT_VARIABLE _lock_result)
if(NOT _lock_result STREQUAL "0")
    message(FATAL_ERROR "Cannot acquire AtomForge build lock: ${_lock_result}")
endif()
execute_process(COMMAND ${_command} RESULT_VARIABLE _command_result)
if(NOT _command_result STREQUAL "0")
    message(FATAL_ERROR "AtomForge build command failed: ${_command_result}")
endif()
